version: '3.5'

services:
  lumen:
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
#      - ./nginx.conf:/etc/nginx/nginx.conf
    build: .
    command: php -S lumen:9000 -t public
    restart: always
